package tests

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/kika1s1/task_manager/domain"
	"github.com/kika1s1/task_manager/usecases"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

func (m *MockTaskRepository) CreateTask(task domain.Task) error {
	args := m.Called(task)
	return args.Error(0)
}

func (m *MockTaskRepository) GetTasks() ([]domain.Task, error) {
	args := m.Called()
	return args.Get(0).([]domain.Task), args.Error(1)
}

func (m *MockTaskRepository) GetTaskByID(id primitive.ObjectID) (domain.Task, error) {
	args := m.Called(id)
	return args.Get(0).(domain.Task), args.Error(1)
}

func (m *MockTaskRepository) UpdateTask(id primitive.ObjectID, updatedTask domain.Task) error {
	args := m.Called(id, updatedTask)
	return args.Error(0)
}

func (m *MockTaskRepository) DeleteTask(id primitive.ObjectID) error {
	args := m.Called(id)
	return args.Error(0)
}



func TestCreateTask(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	task := domain.Task{
		Title:       "Test Task",
		Description: "This is a test task",
	}

	mockRepo.On("CreateTask", task).Return(nil)

	payload, _ := json.Marshal(task)
	req, _ := http.NewRequest("POST", "/tasks", bytes.NewBuffer(payload))
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.CreateTask(c)

	assert.Equal(t, http.StatusCreated, w.Code)
	assert.JSONEq(t, `{"message": "Task created successfully"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestCreateTask_Error(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	task := domain.Task{
		Title:       "Test Task",
		Description: "This is a test task",
	}

	mockRepo.On("CreateTask", task).Return(errors.New("creation error"))

	payload, _ := json.Marshal(task)
	req, _ := http.NewRequest("POST", "/tasks", bytes.NewBuffer(payload))
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.CreateTask(c)

	assert.Equal(t, http.StatusInternalServerError, w.Code)
	assert.JSONEq(t, `{"error": "creation error"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestGetTasks(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	tasks := []domain.Task{
		{Title: "Task 1", Description: "Description 1"},
		{Title: "Task 2", Description: "Description 2"},
	}

	mockRepo.On("GetTasks").Return(tasks, nil)

	req, _ := http.NewRequest("GET", "/tasks", nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.GetTasks(c)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.JSONEq(t, `[{"Title":"Task 1","Description":"Description 1"},{"Title":"Task 2","Description":"Description 2"}]`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestGetTasks_Error(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	mockRepo.On("GetTasks").Return(nil, errors.New("fetch error"))

	req, _ := http.NewRequest("GET", "/tasks", nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.GetTasks(c)

	assert.Equal(t, http.StatusInternalServerError, w.Code)
	assert.JSONEq(t, `{"error": "fetch error"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestGetTaskByID(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	id, _ := primitive.ObjectIDFromHex("605c72ef50f41b0a8e5b4c1e")
	task := domain.Task{
		Title:       "Test Task",
		Description: "This is a test task",
	}

	mockRepo.On("GetTaskByID", id).Return(task, nil)

	req, _ := http.NewRequest("GET", "/tasks/"+id.Hex(), nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.GetTaskByID(c)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.JSONEq(t, `{"Title":"Test Task","Description":"This is a test task"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestGetTaskByID_InvalidID(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	req, _ := http.NewRequest("GET", "/tasks/invalidID", nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.GetTaskByID(c)

	assert.Equal(t, http.StatusBadRequest, w.Code)
	assert.JSONEq(t, `{"error": "Invalid ID format"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestGetTaskByID_NotFound(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	id, _ := primitive.ObjectIDFromHex("605c72ef50f41b0a8e5b4c1e")

	mockRepo.On("GetTaskByID", id).Return(domain.Task{}, errors.New("task not found"))

	req, _ := http.NewRequest("GET", "/tasks/"+id.Hex(), nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.GetTaskByID(c)

	assert.Equal(t, http.StatusNotFound, w.Code)
	assert.JSONEq(t, `{"error": "Task not found"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestUpdateTask(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	id, _ := primitive.ObjectIDFromHex("605c72ef50f41b0a8e5b4c1e")
	updatedTask := domain.Task{
		Title:       "Updated Task",
		Description: "This is an updated task",
	}

	mockRepo.On("UpdateTask", id, updatedTask).Return(nil)

	payload, _ := json.Marshal(updatedTask)
	req, _ := http.NewRequest("PUT", "/tasks/"+id.Hex(), bytes.NewBuffer(payload))
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.UpdateTask(c)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.JSONEq(t, `{"message": "Task updated successfully"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestUpdateTask_InvalidID(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	req, _ := http.NewRequest("PUT", "/tasks/invalidID", nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.UpdateTask(c)

	assert.Equal(t, http.StatusBadRequest, w.Code)
	assert.JSONEq(t, `{"error": "Invalid ID format"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestUpdateTask_Error(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	id, _ := primitive.ObjectIDFromHex("605c72ef50f41b0a8e5b4c1e")
	updatedTask := domain.Task{
		Title:       "Updated Task",
		Description: "This is an updated task",
	}

	mockRepo.On("UpdateTask", id, updatedTask).Return(errors.New("update error"))

	payload, _ := json.Marshal(updatedTask)
	req, _ := http.NewRequest("PUT", "/tasks/"+id.Hex(), bytes.NewBuffer(payload))
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.UpdateTask(c)

	assert.Equal(t, http.StatusInternalServerError, w.Code)
	assert.JSONEq(t, `{"error": "update error"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestDeleteTask(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	id, _ := primitive.ObjectIDFromHex("605c72ef50f41b0a8e5b4c1e")

	mockRepo.On("DeleteTask", id).Return(nil)

	req, _ := http.NewRequest("DELETE", "/tasks/"+id.Hex(), nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.DeleteTask(c)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.JSONEq(t, `{"message": "Task deleted successfully"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestDeleteTask_InvalidID(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	req, _ := http.NewRequest("DELETE", "/tasks/invalidID", nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.DeleteTask(c)

	assert.Equal(t, http.StatusBadRequest, w.Code)
	assert.JSONEq(t, `{"error": "Invalid ID format"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}

func TestDeleteTask_Error(t *testing.T) {
	mockRepo := new(MockTaskRepository)
	usecase := usecases.NewTaskUsecase(mockRepo)

	id, _ := primitive.ObjectIDFromHex("605c72ef50f41b0a8e5b4c1e")

	mockRepo.On("DeleteTask", id).Return(errors.New("delete error"))

	req, _ := http.NewRequest("DELETE", "/tasks/"+id.Hex(), nil)
	w := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(w)
	c.Request = req

	usecase.DeleteTask(c)

	assert.Equal(t, http.StatusInternalServerError, w.Code)
	assert.JSONEq(t, `{"error": "delete error"}`, w.Body.String())
	mockRepo.AssertExpectations(t)
}
